### ISSUE TITLE
Платформа - клиент

### ISSUE THREAD

**Issue by DDHunter13** [DDHunter13/Mem-bot#2]
Рассмотреть вариант создания собственного телеграмм клиента. Т.е. как подключиться, какой интерфейс, методы для отправки сообщений, чтения, и всего такого. Плюсом будет пример какого-нибудь кода или готовой приложки открытой

**Comment by physhock** [comment]
https://core.telegram.org/tdlib
Можно закрывать. На мой взгляд, создавать свой клиент это слишком жирно.

**Comment by kilinochi** [comment]
https://drive.google.com/file/d/1KZH3wH9C4A2e7qPqlNHrx50LoGP6Jx4z/view?usp=sharing
Отчет собснно
