### ISSUE TITLE
Парс HTML страницы

### ISSUE THREAD

**Issue by DDHunter13** [DDHunter13/Mem-bot#9]
Задача - получить картинки из HTML страницы.
Вход - HTML код
Выход - Картинки с мемами
Примечание - Язык Java.

Сайты с мемами:

http://admem.ru/search/%D0%A5%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B3%D0%BE-%D0%B2%D0%B0%D0%BC-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%B8%D1%8F

http://1001mem.ru/search?q=%D0%BE%D0%B2%D0%BE%D1%89

HTML их можно получить из браузера (Chrome - F12)

**Comment by kilinochi** [comment]
Собственно, 1001mem.ru парситься, admem - нет
Универсальный код для парсинга ниже
https://pastebin.com/cPuuk9HR
